### ISSUE TITLE
Meters in my area

### ISSUE THREAD

**Issue by mrwildbob** [seanauff/metermon#25]
Hi Sean, 

Thanks for the project.  In my neighborhood, we are using Neptune E-Coder r450i water meters.  Been running Metermon for a week now. I so not see any of the water meters in the area.  The MQTT messages are the R900, SCM+ and SCM Protocols. I do see 3 water meters that use R900 and the rest are Gas meters with SCM. I also see a few Electric meters showing up as SCM.  Not sure of the brand.  My electric meter is a Landis+Gyr (Gridstream RF ZigBee).  There should be a ton of them in the area. 

I found a good article on my meter:  https://wiki.recessim.com/view/Gr-smart_meters_Setup_Guide

Does Metermon support the r450i and Gr meters?

**Comment by seanauff** [comment]
Metermon supports whatever [rtlamr](https://github.com/bemasher/rtlamr) supports. [Here](https://github.com/bemasher/rtlamr/wiki/Compatible-Meters) is that list of compatible meters. Sometimes metermon doesn't capture everything due to the ERT type not being recognized. If you run rtlamr by itself and do see your meters, then we can troubleshoot metermon. If not, then you will need to use different software to receive those.

**Comment by mrwildbob** [comment]
Thanks for the reply.  Im having the hardest time installing GoLang just to
compile rtlamr.  Guess I need some sleep.

boB
